---
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/artifacts/python-library.yaml

variables:
  LANGUAGE_VERSION: python3.10
  PYTHON_MULTIPROCESSING_START_METHOD: "fork"
  OPENSSL_CONF: "/dev/null"

tox:
  parallel:
    matrix:
      - LANGUAGE_VERSION: [python3.10, python3.11, python3.12, python3.13, python3.14]
