name: ci
on:
  push:
    branches:
      - develop
      - release/**
      - hotfix/**
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          # macos-15 hits end-of-life in January 2028
          - macos-15
          - macos-15-intel
          # Ubuntu 22.04 hits end-of-life in June 2027
          - ubuntu-22.04
          # Windows 2022 mainstream support ends October 2026
          # Windows 2022 extended support ends October 2031
          - windows-2022
        python:
          # Python 3.11 hits end-of-life in October 2027
          - "3.11"
    env:
      GDC_CLIENT_ZIP: 'gdc-client.zip'
      UV_INDEX_URL: "https://pypi.org/simple"
    steps:
      - uses: actions/checkout@v4
        with:
          # required for setuptools_scm to correctly version: https://github.com/pypa/setuptools_scm/issues/480
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
      - name: Run Tests
        env:
          NO_PROXY: "127.0.0.1,localhost"
        run: uvx --with tox-uv tox
      - name: Package
        run: |
          cd bin
          uv run bash ./package
          echo "GDC_CLIENT_ZIP=$GDC_CLIENT_ZIP" >> $GITHUB_ENV
        shell: bash
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.GDC_CLIENT_ZIP }}-py${{ matrix.python }}-${{ matrix.os }}
          path: bin/gdc-client_*.zip
